### ISSUE TITLE
Display on some iOs versions

### ISSUE THREAD

**Issue by Oupsla** [convoo/login-fire#97] opened 2017-05-04 14:42 UTC
Hello 

I notice an error of display on some versions of iOs.
I tested this on BrowserStack.

![capture du 2017-05-04 16-33-06](https://cloud.githubusercontent.com/assets/15279620/25708919/331a2b94-30e8-11e7-9bbb-f14ee1d8c860.png)

**Comment by bkawk** [comment] 2017-05-05 23:05
Is this on an iPhone 7 Plus? Do you have a link to the public site I can check out?
A quick fix maybe to put the component in a div with a slightly smaller max-width.

**Comment by Oupsla** [comment] 2017-05-06 09:38
Its a iPhone 6S on https://www.browserstack.com/

I have prepared a demo here : https://airbar-b0057.firebaseapp.com/
Hope it can help !

(I'm using the v2 branch of login-fire)

**Comment by Oupsla** [comment] 2017-05-06 09:53
And you are right about the div with a smaller max-width.

I have tried this with a div with a max-width of 250px and it's working partially. Buttons are now render correctly but the login-fire element is stuck on the left of the screen

![capture du 2017-05-06 11-51-00](https://cloud.githubusercontent.com/assets/15279620/25771462/8c67d316-3252-11e7-8ae6-fc288a3a2a15.png)

**Comment by bkawk** [comment] 2017-05-07 11:55
Thank you for preparing the demo, I will be looking at resolving this issue this week

**Comment by bkawk** [comment] 2017-05-07 12:02
I just had a look in the Chrome mobile view and I can't reproduce the issue, I'm guessing with Browserstack I will be able to reproduce it?

<img width="383" alt="screen shot 2017-05-07 at 8 01 10 pm" src="https://cloud.githubusercontent.com/assets/14357697/25780743/fa9e5b6c-335f-11e7-9d68-7b2993a37d93.png">

**Comment by Oupsla** [comment] 2017-05-07 12:07
Yes the problem does not appear with Chrome mobile (with iPhone 6 selected).

If you don't have a iPhone to test it, you can test it on BrowserStack yeah (or maybe with Safari but I'm not sure about this)

**Comment by bkawk** [comment] 2017-05-07 12:13
On an actual iPhone it looks like the attached for me,  I will check it on Browser Stack too

![wechatimg1 1](https://cloud.githubusercontent.com/assets/14357697/25780831/61513d88-3361-11e7-9f33-97b01919aa41.jpeg)

**Comment by bkawk** [comment] 2017-05-07 12:33
The browserstack emulator does however render it incorrectly

<img width="657" alt="screen shot 2017-05-07 at 8 32 41 pm" src="https://cloud.githubusercontent.com/assets/14357697/25780950/5ecbd502-3364-11e7-88f7-6cbb370e71c5.png">

**Comment by bkawk** [comment] 2017-05-07 12:54
I have requested free access to BrowserStack as we are an open source project. I have found the two below css changes fix the issue, I'm now keen to see the impact on all the other browser types.

<img width="1057" alt="screen shot 2017-05-07 at 8 52 53 pm" src="https://cloud.githubusercontent.com/assets/14357697/25781100/3869445a-3367-11e7-804d-0fd5d5fdaed1.png">
<img width="1065" alt="screen shot 2017-05-07 at 8 45 45 pm" src="https://cloud.githubusercontent.com/assets/14357697/25781101/386ae044-3367-11e7-9cc0-f18776c9a7e3.png">

**Comment by bkawk** [comment] 2017-05-07 13:39
I need to wait for BrowserStack to approve the open source request before i can continue to investigate this. I suspect this is an issue with the BrowserStack emulator but I'm not sure at this point.

<img width="802" alt="screen shot 2017-05-07 at 9 38 04 pm" src="https://cloud.githubusercontent.com/assets/14357697/25781477/7f114df2-336d-11e7-8ae3-dd6c9a6b8d52.png">

**Comment by Oupsla** [comment] 2017-05-07 13:54
I have detected this issue on a real iPhone 6 last week (was not mine), that's why I have tested this on browser stack.

Tuesday I will retry on this iPhone and I'll keep you in touch !

**Comment by Oupsla** [comment] 2017-05-13 09:19
Any news about BrowserStack ?
I confirm that on some versions of iOs, the menu is displayed like in BrowserStack

**Comment by Oupsla** [comment] 2017-05-23 11:03
Any news ?

**Comment by sbeleidy** [comment] 2017-05-29 17:39
Hey, just to make sure I'm caught up with this - you're using login-fire v2 on an iphone6s on browserstack, right?

Could you update to the latest v2? I'm wondering if #103 fixes this as well.

**Comment by Oupsla** [comment] 2017-05-29 18:53
Yeah this is exactly what I'm doing cause I don't have a iPhone to test on it.

I have update to the latest v2 and this is not fixing this bug 😞 
(The workaround that @bkawk proposed works btw)

**Comment by Oupsla** [comment] 2017-05-29 18:58
I also noticed a bug with the icons in the buttons

**Comment by Oupsla** [comment] 2017-05-29 18:59
I also noticed a display bug with the icons in the buttons

**Comment by Oupsla** [comment] 2017-05-29 19:01
I also noticed another display bug with the icons in the buttons (on iOs).

Because of missing semicolons in the file login-fire-button.html, --apply do not work and do not apply (should I create another issue for this ?)

**Comment by sbeleidy** [comment] 2017-05-29 19:03
I will try and implement his solution - if not, you might have to wait till he gets to it.

Yes, please create another issue for that with more details explaining the issue.

**Closed as completed** 2017-06-16 10:11 UTC
Labels: bug
